repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
        - id: check-byte-order-marker
        - id: trailing-whitespace
          exclude: '.*\.patch'
        - id: check-docstring-first
        - id: check-executables-have-shebangs
        - id: check-json
        - id: check-xml
        - id: check-yaml
        - id: check-merge-conflict
        - id: check-symlinks
        - id: end-of-file-fixer
        - id: mixed-line-ending
          args: [--fix=lf]

  - repo: local
    hooks:
      -   id: clang-format
          name: Run clang-format
          description: Clang C/C++ code formatter.
          entry: clang-format -i
          args: [-style=file]
          language: system
          types: [file, c++]
        # note: formatting style in .clang-format
